// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaSachAPI.Models;

#nullable disable

namespace QuanLyNhaSachAPI.Migrations
{
    [DbContext(typeof(QuanLyNhaSachContext))]
    [Migration("20260515014849_FixForeignKey_DonDatHang")]
    partial class FixForeignKey_DonDatHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.ChiTietDonDatHang", b =>
                {
                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Slsach")
                        .HasColumnType("int")
                        .HasColumnName("SLSach");

                    b.HasKey("MaDh", "MaSach")
                        .HasName("PK__ChiTietD__EC06D12342A4BA5F");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietDonDatHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.DonDatHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<string>("DiaChiGh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DiaChiGH");

                    b.Property<int?>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<string>("MaVanDon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TrangThaiDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaDh")
                        .HasName("PK__DonDatHa__2725866111C3ACAF");

                    b.HasIndex("MaNd");

                    b.HasIndex("MaNguoiDuyet");

                    b.ToTable("DonDatHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.GioHang", b =>
                {
                    b.Property<int>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int?>("TongSlsach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("TongSLSach");

                    b.HasKey("MaNd", "MaSach")
                        .HasName("PK__GioHang__EC068066B8D4412E");

                    b.HasIndex("MaSach");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiTt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThaiTT");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E03D1FDACB");

                    b.HasIndex(new[] { "MaDh" }, "UQ__HoaDon__27258660682DFF8C")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.KhachHang", b =>
                {
                    b.Property<int>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<bool?>("TrangThaiTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThaiTK");

                    b.HasKey("MaNd")
                        .HasName("PK__KhachHan__2725D7248678DFF4");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNd"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenND");

                    b.HasKey("MaNd")
                        .HasName("PK__NguoiDun__2725D7246BA112F9");

                    b.HasIndex(new[] { "TenNd" }, "UQ__NguoiDun__4CF9B49A554A5111")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534E8753DD0")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NguoiQuanTri", b =>
                {
                    b.Property<int>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaNd")
                        .HasName("PK__NguoiQua__2725D7248A7FF95D");

                    b.ToTable("NguoiQuanTri", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNxb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNXB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNxb"));

                    b.Property<string>("TenNxb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNXB");

                    b.HasKey("MaNxb")
                        .HasName("PK__NhaXuatB__3A19482C8C8E520E");

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("MaNxb")
                        .HasColumnType("int")
                        .HasColumnName("MaNXB");

                    b.Property<int?>("MaTg")
                        .HasColumnType("int")
                        .HasColumnName("MaTG");

                    b.Property<int?>("MaTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTL");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Slton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SLTon");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThaiS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaSach")
                        .HasName("PK__Sach__B235742DD46005CB");

                    b.HasIndex("MaNxb");

                    b.HasIndex("MaTg");

                    b.HasIndex("MaTl");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.TacGium", b =>
                {
                    b.Property<int>("MaTg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTg"));

                    b.Property<string>("TenTg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTG");

                    b.HasKey("MaTg")
                        .HasName("PK__TacGia__272500740870C41F");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTl"));

                    b.Property<string>("TenTl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTL");

                    b.HasKey("MaTl")
                        .HasName("PK__TheLoai__272500717CF3806F");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.ChiTietDonDatHang", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.DonDatHang", "MaDhNavigation")
                        .WithMany("ChiTietDonDatHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__45F365D3");

                    b.HasOne("QuanLyNhaSachAPI.Models.Sach", "MaSachNavigation")
                        .WithMany("ChiTietDonDatHangs")
                        .HasForeignKey("MaSach")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaSac__46E78A0C");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSachNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.DonDatHang", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.KhachHang", "MaNdNavigation")
                        .WithMany("DonDatHangs")
                        .HasForeignKey("MaNd")
                        .HasConstraintName("FK__DonDatHang__MaND__4316F928");

                    b.HasOne("QuanLyNhaSachAPI.Models.NguoiQuanTri", "NguoiQuanTri")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet");

                    b.Navigation("MaNdNavigation");

                    b.Navigation("NguoiQuanTri");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.GioHang", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.KhachHang", "MaNdNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNd")
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__MaND__3D5E1FD2");

                    b.HasOne("QuanLyNhaSachAPI.Models.Sach", "MaSachNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaSach")
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__MaSach__3E52440B");

                    b.Navigation("MaNdNavigation");

                    b.Navigation("MaSachNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.DonDatHang", "MaDhNavigation")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyNhaSachAPI.Models.HoaDon", "MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaDH__4BAC3F29");

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.NguoiDung", "MaNdNavigation")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyNhaSachAPI.Models.KhachHang", "MaNd")
                        .IsRequired()
                        .HasConstraintName("FK__KhachHang__MaND__2F10007B");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NguoiQuanTri", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.NguoiDung", "MaNdNavigation")
                        .WithOne("NguoiQuanTri")
                        .HasForeignKey("QuanLyNhaSachAPI.Models.NguoiQuanTri", "MaNd")
                        .IsRequired()
                        .HasConstraintName("FK__NguoiQuanT__MaND__32E0915F");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.Sach", b =>
                {
                    b.HasOne("QuanLyNhaSachAPI.Models.NhaXuatBan", "MaNxbNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaNxb")
                        .HasConstraintName("FK__Sach__MaNXB__398D8EEE");

                    b.HasOne("QuanLyNhaSachAPI.Models.TacGium", "MaTgNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaTg")
                        .HasConstraintName("FK__Sach__MaTG__38996AB5");

                    b.HasOne("QuanLyNhaSachAPI.Models.TheLoai", "MaTlNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaTl")
                        .HasConstraintName("FK__Sach__MaTL__37A5467C");

                    b.Navigation("MaNxbNavigation");

                    b.Navigation("MaTgNavigation");

                    b.Navigation("MaTlNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.DonDatHang", b =>
                {
                    b.Navigation("ChiTietDonDatHangs");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.KhachHang", b =>
                {
                    b.Navigation("DonDatHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NguoiQuanTri");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.Sach", b =>
                {
                    b.Navigation("ChiTietDonDatHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.TacGium", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyNhaSachAPI.Models.TheLoai", b =>
                {
                    b.Navigation("Saches");
                });
#pragma warning restore 612, 618
        }
    }
}
